spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///demo
    username: root
    password: 12345678
  redis:
    host: localhost
    port: 6379
    database: 0
    username: root
    password: 12345678
  elasticsearch:
    uris: localhost:9200
    connection-timeout: 1s
    socket-timeout: 30s
    username: elastic
    password: 12345678
  rabbitmq:
    addresses: localhost:5672
    virtual-host: /
    username: root
    password: 12345678
    publisher-confirm-type: correlated
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
      queue: queue.default
    template:
      exchange:
        delay: exchange.delay.default
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: baseline
    baseline-version: 0.0.1
  minio:
    endpoint: http://localhost:9066
    server-host: http://localhost:9066
    access-key: root
    secret-key: 12345678
  retrofit:
    server-hosts:
      - server-id: default
        server-host: http://localhost:9169
      - server-id: second
        server-host: https://www.baidu.com