spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///demo
    username: root
    password: 12345678
  redis:
    host: localhost
    port: 6379
    database: 0
    username: root
    password: 12345678
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: baseline
    baseline-version: 0.0.1