server:
  port: 8080

spring:
  application:
    name: formwork
  profiles:
    default: development
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: redis
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
      isolation-level-for-create: default
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  jpa:
    open-in-view: false

springdoc:
  paths-to-match: /*
  paths-to-exclude: /error
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ui-docs

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics